version: "3.2"

services:
  alice:
    build:
      context: ./alice
      dockerfile: Dockerfile
    working_dir: /app
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - app-net
    depends_on:
      - bob

  bob:
    build:
      context: ./bob
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8081:8081
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
